package key;

/*
 * Keyinputdetails.java
 *
 * Created on March 25, 2010, 2:33 AM
 */



/**
 *
 * @author  jenniferschofield
 */
public class Keyinputdetails extends javax.swing.JPanel {
    KeyButton keyb;
    char k;
        /** Creates new form Keyinputdetails */
    public Keyinputdetails(KeyButton kb,char ke) {
        keyb=kb;
        k=ke;
        initComponents();
        button.setText(java.lang.Character.toString(ke));
        key.setText(java.lang.Character.toString(ke));
        generator.setText(java.lang.Character.toString(ke));
    }
    /** Creates new form Keyinputdetails */
    public Keyinputdetails(KeyButton k,String g, String t, char ke) {
        keyb=k;
        initComponents();
        button.setText(t);
        key.setText(java.lang.Character.toString(ke));
        generator.setText(g);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        key = new javax.swing.JLabel();
        generator = new javax.swing.JTextField();
        button = new javax.swing.JTextField();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        key.setText(java.lang.Character.toString(k));
        add(key);

        generator.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                generatorFocusLost(evt);
            }
        });
        add(generator);

        button.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                buttonFocusLost(evt);
            }
        });
        add(button);
    }// </editor-fold>//GEN-END:initComponents

private void generatorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_generatorFocusLost
     keyb.frase=generator.getText();
}//GEN-LAST:event_generatorFocusLost

private void buttonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buttonFocusLost
     keyb.button.setText(button.getText());
}//GEN-LAST:event_buttonFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField button;
    public javax.swing.JTextField generator;
    private javax.swing.JLabel key;
    // End of variables declaration//GEN-END:variables

}
